language: python
python:
  - "2.7.13"
  - "2.7.14"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  
#  - "pypy"
#  - "pypy3"

install:
  - pip install .

script:
  - PYTHONPATH=.:$PYTHONPATH ./test-travis.sh

